### ISSUE TITLE
Add concat support

### ISSUE THREAD

**Issue by x-christian-romeni** [leafymind/gulp-sass-themes#11]
It would be awesome to have concat support. I'm not sure how the two files are handled further down the pipe...

**Comment by bbuhler** [comment]
I suggested two possible options, which don't require any change to this plugin:

1. You create one main SASS file that includes all other files, so you have only one file per theme in the pipeline. This can also be automatized by using [gulp-inject](https://github.com/klei/gulp-inject/issues/49) for example.
2. You use a combination of [gulp-concat](https://www.npmjs.com/package/gulp-concat) and [gulp-filter](https://www.npmjs.com/package/gulp-filter) or [gulp-if](https://www.npmjs.com/package/gulp-if).
