### ISSUE TITLE
how to get an example of this sass source file structures for working 

### ISSUE THREAD

**Issue by ebrahim-tadbir** [leafymind/gulp-sass-themes#4]
hi
what should be available in body.themed.sass

I have a folder named "themes" and the colors are there but doesn't know how to apply this code,
i'm not sure, I'm doing the right way:

I also receive this error:

/Users/ebrahim/node_modules/gulp-sass-themes/sass-themes.js:13
    themeImports[themeName] = new Buffer(`$current-theme-name: "${themeName}";
                                         ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ebrahim/Dropbox/PROJECTS/imco/imco-fa/gulpfile.js:15:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by bbuhler** [comment]
Hi @ebrahim-tadbir,

I added and example with 676c32f.

Which NodeJS version are you using?
Since the code is written in EcmaScript 2015 you probably need to use at least the latest LTS version.

**Comment by ebrahim-tadbir** [comment]
Hi thanks for answering
here is my version
[sass.zip](https://github.com/bbuhler/gulp-sass-themes/files/285934/sass.zip)

s-MacBook-Pro:~ ebrahim$ node -v
v0.12.7

I don't know what is happening to my sass files.
please help me

**Comment by ebrahim-tadbir** [comment]
is that ok now with my latest version og nodejs?
s-MacBook-Pro:~ ebrahim$ sudo n stable

```
 install : node-v6.2.0
   mkdir : /usr/local/n/versions/node/6.2.0
   fetch : https://nodejs.org/dist/v6.2.0/node-v6.2.0-darwin-x64.tar.gz
```

######################################################################## 100.0%
   installed : v6.2.0

**Comment by bbuhler** [comment]
> is that ok now with my latest version og nodejs?
> [..]
> installed : v6.2.0

Yes, did you still get the error message?

> I don't know what is happening to my sass files.
> please help me

What you mean?

You may need to add the `.themed.` placeholder to the file you want to be themed.
Also the theme files are meant to contain only variables.

Just check the example to see how it works.
