### ISSUE TITLE
Custom theme for each file

### ISSUE THREAD

**Issue by mabar** [leafymind/gulp-sass-themes#8]
It would be nice have option to use custom theme for each file.
For example, I have public.scss and admin.scss, both with themes. And themes for both have different configuration.

Files in themes folder would be in format like _FILE.THEME.scss

**Comment by TeakOhms** [comment]
I have the same need there. I did have that working at one point but i'm not sure i ever made a PR

**Comment by O-Mutt** [comment]
I have the same need there. I did have that working at one point but i'm not sure i ever made a PR

**Comment by bbuhler** [comment]
You can achieve this by combine it with other plugins like `gulp-filter`.

```javascript
const gulp = require('gulp');
const sass = require('gulp-sass');
const sassThemes = require('gulp-sass-themes');
const filter = require('gulp-filter');

const onlyPublic = filter('**/public.scss', { restore: true });
const onlyAdmin = filter('**/admin.scss', { restore: true });

gulp.task('styles', () => gulp.src('./styles/**/*.scss')
    .pipe(onlyPublic)
    .pipe(sassThemes('./styles/themes/_public.*.scss'))
    .pipe(onlyPublic.restore)
    .pipe(onlyAdmin)
    .pipe(sassThemes('./styles/themes/_admin.*.scss'))
    .pipe(onlyAdmin.restore)
    .pipe(sass()).on('error', sass.logError)
    .pipe(gulp.dest('./dist/styles'))
);
```

**Comment by mabar** [comment]
And with iteration throught all files in themes directory it should be universal. 
Nice solution. Thank you.
